# This file contains the set of jobs run by the pixman project:
# https://gitlab.freedesktop.org/pixman/pixman/-/pipelines
spec:
  inputs:
    active_target_pattern:
    runner_tag_amd64:
    runner_tag_qemu:
    runner_tag_arm64:
---

stages:
  - docker
  - build
  - test
  - summary

variables:
  # Docker image global configuration.
  DOCKER_TAG: latest
  DOCKER_REGISTRY_IMAGE: registry.freedesktop.org/pixman/pixman
  DOCKER_NAME_FULL: ${DOCKER_REGISTRY_IMAGE}/pixman:${DOCKER_TAG}-${TARGET}

  # Execute to load a target-specific environment.
  LOAD_TARGET_ENV: source .gitlab-ci.d/01-docker/target-env/${TARGET}.env

workflow:
  rules:
    # Use modified Docker image if building in MR and Docker image is affected
    # by the MR.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        paths:
          - .gitlab-ci.d/01-docker.yml
          - .gitlab-ci.d/01-docker/**/*
      variables:
        DOCKER_TAG: $CI_COMMIT_REF_SLUG
        DOCKER_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

    # A standard set of GitLab CI triggers (i.e., MR, schedule, default branch,
    # and tag).
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'web'

  auto_cancel:
    on_new_commit: conservative
    on_job_failure: all

default:
  # Retry in case the runner is misconfigured for multi-arch builds or some
  # random unexpected runner error occurs (it happened during testing).
  retry: 1

include:
  - local: "/.gitlab-ci.d/templates/targets.yml"
    inputs:
      active_target_pattern: $[[ inputs.active_target_pattern ]]
  - local: "/.gitlab-ci.d/01-docker.yml"
    inputs:
      active_target_pattern: $[[ inputs.active_target_pattern ]]
      runner_tag_amd64: $[[ inputs.runner_tag_amd64 ]]
      runner_tag_qemu: $[[ inputs.runner_tag_qemu ]]
      runner_tag_arm64: $[[ inputs.runner_tag_arm64 ]]
  - local: "/.gitlab-ci.d/02-build.yml"
    inputs:
      runner_tag_amd64: $[[ inputs.runner_tag_amd64 ]]
      runner_tag_qemu: $[[ inputs.runner_tag_qemu ]]
      runner_tag_arm64: $[[ inputs.runner_tag_arm64 ]]
  - local: "/.gitlab-ci.d/03-test.yml"
    inputs:
      runner_tag_amd64: $[[ inputs.runner_tag_amd64 ]]
      runner_tag_qemu: $[[ inputs.runner_tag_qemu ]]
      runner_tag_arm64: $[[ inputs.runner_tag_arm64 ]]
  - local: "/.gitlab-ci.d/04-summary.yml"
    inputs:
      runner_tag_amd64: $[[ inputs.runner_tag_amd64 ]]
